# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='product',
        ),
    ]
