# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_items', '0002_auto_20160128_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
